### ISSUE TITLE
Error with updates (26.07.2023)

### ISSUE THREAD

**Issue by aHafiz11** [nikolaos-siomos/ATLAS#2] opened 2023-07-27 12:48 UTC
Hi @Nikos,

I tried to rerun ATLAS again with the updated version (26.07.2023), I also updated the config and setting files following the updates.
But I encountered these issues related to 

> TypeError: ufunc 'deg2rad' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

I have attached the error message :
![image](https://github.com/nikolaos-siomos/ATLAS/assets/87298036/a495bbfa-87ae-4af7-a304-5de888b3d96c)

Are these issues might originate from the wrong information inserted in the new version of the config and setting files?

Best,

**Comment by nikolaos-siomos** [comment] 2023-07-27 21:35
Hi @aHafiz11,

I was able to reproduce the error. It occurred when providing the zenith_angle manually in the config_file.ini.
The problem is fixed in v0.4.1

Best

**Closed as completed** 2023-07-28 09:42 UTC
